### ISSUE TITLE
How to update user's app_metadata

### ISSUE THREAD

**Issue by tbrains** [supabase-community/gotrue-py#132]
How to update app_metadata similar to javascript client's [updateUserById](https://supabase.com/docs/reference/javascript/auth-api-updateuserbyid)?

**Comment by J0** [comment]
Hey @tbrains,

Apologies for the delayed reply - this should be addressed in #169 we'll be porting over `updateUserById` soon. Going to close this issue now in favour of tracking on #169 but feel free to re-open if there are further issues.

Thanks!
Joel
