### ISSUE TITLE
Create User without needing to confirm the email

### ISSUE THREAD

**Issue by odiseo0** [supabase-community/gotrue-py#135]
I'd like that when creating a user with `create_user` from the GoTrueAPI doesn't needs email confirmation, since in the Supabase panel I can't confirm the email. 
It becomes painful to try to confirm the email, how could we create a User without needing to confirm its email?
The confirmation email option is also disabled, does the `data` in `UserAttributes` can have a property like `confirmed:true`?

**Comment by leynier** [comment]
Do you mean that you want that the user creation process allows you to set up whether or not the email needs to be confirmed based on a property of `User ]Attributes` data?

**Comment by odiseo0** [comment]
Not exactly, I was just wondering if setting a property of `UserAttributes` could help me achieve this.
I only don't want to confirm the email when I create a use with the `create_user` method

**Comment by leynier** [comment]
It is possible to turn off email confirmations at all.

I'm not sure about this, but, I think that to choose that be active only when creations come from the client side and not when coming from the server side is not possible right now.

I highly recommend you to ask in the https://github.com/supabase/gotrue repo.

If anyone knows the answer or has a suggestion about it, please share it.

**Comment by odiseo0** [comment]
Ok, thank you

**Comment by odiseo0** [comment]
Solved the problem with the following, with `pydantic` I extended the class `UserAttributes` to accept a parameter called `email_confirm`.

Reference: [gotrue-js](https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#:~:text=export%20interface%20AdminUserAttributes%20extends%20UserAttributes)

**Comment by odiseo0** [comment]
Also, I'll make a PR extending `UserAttributes` to an `UserAdminAttributes` later
