### ISSUE TITLE
Response dataclasses models instead of dicts

### ISSUE THREAD

**Issue by leynier** [supabase-community/gotrue-py#15]
Working with dictionaries in the responses makes the development tedious process, it would be good if the response of the methods were dataclasses.

The types can be found in the [gotrue-js](https://github.com/supabase/gotrue-js) documentation: <https://supabase.github.io/gotrue-js>

We can use [pydantic](https://pydantic-docs.helpmanual.io) as it brings validation and deserialization or else uses dataclasses and implement deserialization by ourselves.

I wait for feedback, I'm willing to work on the pull request.

**Comment by J0** [comment]
Hey @leynier,

Thanks for the suggestion! I think dataclasses make a lot of sense. Please feel free to go for it.

JL
