### ISSUE TITLE
Refresh token event not fired due to wrong unit of time in threading.Timer()

### ISSUE THREAD

**Issue by hern16** [supabase-community/gotrue-py#163]
`threading.Timer()` interval unit is in _second_ **not** _millisecond_

https://github.com/supabase-community/gotrue-py/blob/46668453b0fbb0411af78f171b0dae80c5e2c23f/gotrue/_sync/client.py#L616-L618

and

https://github.com/supabase-community/gotrue-py/blob/46668453b0fbb0411af78f171b0dae80c5e2c23f/gotrue/_async/client.py#L624-L626

**Comment by J0** [comment]
Hey,

Thanks for catching this! You're right, there shouldn't be a need to multiply by 1000 since `Timer` takes in seconds as a unit.

We should be removing the entire `client.py` class soon but I'll adjust it for now
