### ISSUE TITLE
Add support for invite_user_by_email

### ISSUE THREAD

**Issue by gvashishtha** [supabase-community/gotrue-py#166]
# Feature request

## Is your feature request related to a problem? Please describe.

The GoTrue JS client supports [inviting users by email](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L419) which is an important feature in SaaS apps where collaboration is important for success (think Hubspot, Figma, Slack).

## Describe the solution you'd like

There should be a function `invite_user_by_email` in both the `AsyncGoTrueAPI` and the `SyncGoTrueAPI` that takes a required `email` parameter and an optional `redirect_to` parameter to let users invite other users by email.

## Describe alternatives you've considered

Right now what we've chosen to do is write a typescript function that uses the GoTrue-js API. This is not ideal as it means the majority of our codebase is in Python and we have to build separate infrastructure to maintain that tiny bit of Typescript.

The other option would be to use Python's `requests` library to call into the Supabase API directly. We'd then lose all the nice parts of using an SDK (automated retry, helpful error messages, auth) and also be introducing a tight coupling with this version of the Supabase API.

**Comment by J0** [comment]
Hey @gvashishtha,

We support the `invite_user_by_email` under the [admin api](https://github.com/supabase-community/gotrue-py/blob/main/gotrue/_async/api.py#L341)

We'll be updating our documentation soon but for now feel free to let us know if you have any issues

**Comment by J0** [comment]
Going to close for now due to inactivity
