### ISSUE TITLE
Add updateUserById (Auth, server only) for parity with JS features

### ISSUE THREAD

**Issue by scanrsvp** [supabase-community/gotrue-py#169]
Hello. 
I'd like to request the addition of the update_user_by_id method for parity with the JS client.    

## Is your feature request related to a problem? Please describe.    

The `gotrue-py` client is missing a few methods which would be immensely helpful; one of which is [`updateUserById`](https://supabase.com/docs/reference/javascript/auth-api-updateuserbyid). While this (gotrue-py) client does have the [`update_user`](https://github.com/supabase-community/gotrue-py/blob/main/gotrue/_async/api.py#L500) method available, this method relies on a JWT and the RLS system for identifying the user to be updated. The JS client contains server-only methods which rely on the `service_role` keys to operate, and `updateUserById` is one such important method. This method is vital for the administration of users by admin users and system processes. 

## Describe the solution you'd like    

I would simply like to request that this method be added. 

## Describe alternatives you've considered

There are no alternatives, short of constructing the endpoint call manually, which defeats the purpose of using a client.     

Thanks.

**Comment by J0** [comment]
Hey @scanrsvp,

Thanks for the request! This feature is in #148 and should be going out together with [#148](https://github.com/supabase-community/gotrue-py/pull/148) courtesy of @leynier

**Comment by J0** [comment]
Hey we've just merged #148 and this should be in the client. Let us know if there are issues.

Thanks!
