### ISSUE TITLE
Add support for auth.admin endpoints

### ISSUE THREAD

**Issue by altryne** [supabase-community/gotrue-py#216]
**Is your feature request related to a problem? Please describe.**
I want to query the twitter handle of a user who's signed in with twitter

**Describe the solution you'd like**
JS API has auth.admin which takes the service key and is able to return auth stuff
https://supabase.com/docs/reference/javascript/admin-api

**Describe alternatives you've considered**
Writing a middleware with JS and cloudflare worker

**Additional context**
I've tried to use the regular from_ but the auth schema is not exposed via API

**Comment by J0** [comment]
Fixed by #148

**Comment by J0** [comment]
Hey,

Thanks for your patience. We've just merged #148  - do you mind checking if the current set of functions suit your use case?

Let us know!

**Comment by arshamg** [comment]
This is great, certainly covers our use cases at Ribbon 🙏

**Comment by J0** [comment]
Great to hear! Going to close this for now but feel free to re-open if there are any issues
