### ISSUE TITLE
Sign In With OTP XForm has validation errors

### ISSUE THREAD

**Issue by J0** [supabase-community/gotrue-py#231]
How to reproduce- 

Initialize client and call

```python3
data = ath.sign_in_with_otp({
            "email": 'someeperon@supabase.io',
            "options": {
              "email_redirect_to": 'https://example.com/welcome'
            }
          })
```

<img width="1468" alt="CleanShot 2023-02-11 at 20 44 15@2x" src="https://user-images.githubusercontent.com/8011761/218258629-32e91b5c-ca76-456e-89c1-36c67f51c37c.png">

**Comment by hgseo16** [comment]
Seems like when `_request()` from `gotrue_base_api.py` is being invoked, the `result` variable ends up returning an empty dictionary `{}`. The empty dictionary is then thrown into `xform()` which is `parse_auth_response` from `gotrue.helpers.py` causing the error stated above.


```
def parse_auth_response(data: Any) -> AuthResponse:
    session: Union[Session, None] = None
    if (
        "access_token" in data
        and "refresh_token" in data
        and "expires_in" in data
        and data["access_token"]
        and data["refresh_token"]
        and data["expires_in"]
    ):
        session = Session.parse_obj(data)

   # User.parse_obj({}) throws the error in the above screenshot

    user = User.parse_obj(data["user"]) if "user" in data else User.parse_obj(data)
    return AuthResponse(session=session, user=user)

```

I know @J0 is assigned this task but I'd love to work on this issue with a little guidance! What should `parse_auth_response` return when `data = {}` during `auth.sign_in_with_otp()`?

**Comment by J0** [comment]
Hey @hgseo16,

Feel free to work on this. `/otp` should return an empty response, as the user is not signed in at that point. Perhaps we could return an Auth response with a None for session and None for user? Open to other suggestions as well

**Comment by hgseo16** [comment]
Hi @J0! Thank you for your help. 

I agree that an `AuthResponse(user=None, session=None)` response would look consistent with that of `supabase-js`. I've attached a screenshot of `GoTrueClient.ts` for your reference.

<img width="678" alt="supabase-js" src="https://user-images.githubusercontent.com/56215649/232405663-6f573974-14f9-46de-9d0e-ea724477c2d1.png">

I'll open a pull request regarding the small fix below.

<img width="1112" alt="supabase-py" src="https://user-images.githubusercontent.com/56215649/232405601-f5c9fe19-760e-4419-a04a-512cfa1230be.png">

**Comment by silentworks** [comment]
This issue seem to have been fixed by a PR that got merged. Closing this one out.
