### ISSUE TITLE
Google Sign In Base64 Decoding Incorrect Padding

### ISSUE THREAD

**Issue by ethancatzel** [supabase-community/gotrue-py#237]
# Bug report

## Describe the bug

The access token sent in the `supabase.auth.set_session` function fails to decode the base64 string retrieved from Google.

## To Reproduce

Sign in with Google.

```python
import webbrowser

from supabase import create_client, Client

supabase: Client = create_client(url, key)
data = supabase.auth.sign_in_with_oauth({"provider": "google"})

webbrowser.open(data.url)
```

Given successful sign-in, redirects to "http://localhost/auth/?access_token=XXX&refresh_token=YYY". This is a Python Flask server that retrieves this request.
```python
supabase.auth.set_session(
    access_token=request.args["access_token"],
    refresh_token=request.args["refresh_token"],
)
```

## System information

- OS: Mac M1
- Version of gotrue-py: 1.0.0

## Additional context

I found there was similar code for the `gotrue-js` repository here: https://github.com/supabase/gotrue-js/blob/1696fd6920c0e418402695a77ddfe8a24c808e5f/src/lib/helpers.ts#L195

Unfortunately I don't have permissions to make pull requests in this repository. However, here is the diff that should fix this bug (worked on my machine):

```git
diff --git a/gotrue/helpers.py b/gotrue/helpers.py
index 6aa7302..23802c9 100644
--- a/gotrue/helpers.py
+++ b/gotrue/helpers.py
@@ -78,9 +78,15 @@ def handle_exception(exception: Exception) -> AuthError:
         return AuthUnknownError(get_error_message(error), e)


+def decode_base64_url(value: str) -> str:
+    value = value.replace("-", "+").replace("_", "/")
+    value += "=" * (4 - len(value) % 4)
+    return b64decode(value).decode("utf-8")
+
+
 def decode_jwt_payload(token: str) -> Any:
     parts = token.split(".")
     if len(parts) != 3:
         raise ValueError("JWT is not valid: not a JWT structure")
     base64Url = parts[1]
-    return loads(b64decode(base64Url).decode("utf-8"))
+    return loads(decode_base64_url(base64Url))
```

To test these changes, save it to a file called `file.diff` and apply it with `git apply file.diff`.

**Comment by kn** [comment]
I can confirm the same issue. In my case, I fixed it with the following:
```
diff --git a/gotrue/helpers.py b/gotrue/helpers.py
index 6aa7302..adbd14d 100644
--- a/gotrue/helpers.py
+++ b/gotrue/helpers.py
@@ -83,4 +83,7 @@ def decode_jwt_payload(token: str) -> Any:
     if len(parts) != 3:
         raise ValueError("JWT is not valid: not a JWT structure")
     base64Url = parts[1]
-    return loads(b64decode(base64Url).decode("utf-8"))
+    # Addding padding otherwise the following error happens:
+    # binascii.Error: Incorrect padding
+    base64UrlWithPadding = base64Url + '=' * (-len(s) % 4)
+    return loads(b64decode(base64UrlWithPadding).decode("utf-8"))
```

* Google login
* Python 3.10.9
* gotrue-py 1.0.0

**Comment by J0** [comment]
Thanks for looking into this @kn

Feel free to file a PR, else will get to it when available, possibly over the weekend

**Comment by J0** [comment]
Merged the PR, should go out with next release (probably weekend)

**Comment by kn** [comment]
great - thanks!

**Comment by J0** [comment]
Should be fixed with release, closing for now but feel free to re-open if there are still issues
