### ISSUE TITLE
Double encoding of URL query string when using redirect_to in sign_in_with_oauth

### ISSUE THREAD

**Issue by chermdev** [supabase-community/gotrue-py#246]
# Bug report

## Describe the bug
I'm trying to use the `redirect_to` option when authorizing with provider in [sign_in_with_oauth](sign_in_with_oauth) but the URL str value is encoded twice:  

1) from **http://localhost:8000/user/**
2) to **http%3A//localhost%3A8000/user/**
<img src="https://user-images.githubusercontent.com/46976866/223549657-6cd3c66d-d6f4-44d1-a4ca-d41e988e4901.png" width="400px">

3) and finally the request to **http%253A%2F%2Flocalhost%253A8000%2Fuser%2F**
<img src="https://user-images.githubusercontent.com/46976866/223550550-d75716a0-1b76-45f6-b6e4-d17e2a869721.png" width="500px">

This is creating 2 issues, the redirect_to option is not working because it's not matching the allowed redirect urls from Supabase and second, the redirect url is incorrect.

## To Reproduce

1. Sign in with github or any provider and send a redirect_to value

```python
provider = "github"
redirect_to = "http://localhost:8000/user/"

supabase.auth.sign_in_with_oauth({
            "provider": provider,
            "options": {
                "redirect_to": redirect_to
     }
})
```

2. We can debug the value from the [_get_url_for_provider](https://github.com/supabase-community/gotrue-py/blob/3ec751bbc97f6917fd7c3aace24dfb67e23efbda/gotrue/_sync/gotrue_client.py#L256) function in https://github.com/supabase-community/gotrue-py/blob/3ec751bbc97f6917fd7c3aace24dfb67e23efbda/gotrue/_sync/gotrue_client.py#L825-L833

3. at the start of the function the values are: 
```python
provider = "github"
params = {'redirect_to': 'http://localhost:8000/user/'}
```
4. after each `quote(v)` the params are encoded:
https://github.com/supabase-community/gotrue-py/blob/3ec751bbc97f6917fd7c3aace24dfb67e23efbda/gotrue/_sync/gotrue_client.py#L830-L831
```python
params = {'redirect_to':'http%3A//localhost%3A8000/user/', 'provider':'github'}
```
5. then `urlencode(params)` encodes all params again:
https://github.com/supabase-community/gotrue-py/blob/3ec751bbc97f6917fd7c3aace24dfb67e23efbda/gotrue/_sync/gotrue_client.py#L832-L833
```python
query = 'redirect_to=http%253A%2F%2Flocalhost%253A8000%2Fuser%2F&provider=github' 

return f"{self._url}/authorize?{query}"
return f"{self._url}/authorize?redirect_to=http%253A%2F%2Flocalhost%253A8000%2Fuser%2F&provider=github"
```

⚠ Note: I'm using the _sync client, but the same steps are in the _async.

**Comment by J0** [comment]
Thanks for the detailed report  - feel free to file a PR, else will look at it when a slot frees up! Finishing up a tutorial on how to use OAuth with Django so hoping to fix that before the tutorial goes out yeah.

**Comment by silentworks** [comment]
I'm closing this issue since a PR was merged to address it a few months ago. Please comment if the issue still persists and I'll re-open it.
