### ISSUE TITLE
pydantic > 2.1.0 is too restrictive

### ISSUE THREAD

**Issue by olirice** [supabase-community/gotrue-py#291]
## Restrictive Dependency

pydantic's minimum version was bumped from 2.1.0, which was released less than 3 weeks ago.
https://github.com/supabase-community/gotrue-py/blob/c2ed950516e4b9bee6eb8f066969049b9a361a28/pyproject.toml#L20

pydantic is a common dependency, particularly among API building libraries and this makes gotrue-py/supabase-py incompatible with those libs

For example, we are currently incompatible with FastAPI and LangChain

**Comment by olirice** [comment]
same problem as https://github.com/supabase-community/postgrest-py/issues/282

**Comment by sjhansen3** [comment]
+1 on this issue. I'm seeing that a big draw for the Supabase Python client is its use in AI projects. That pydantic version restriction is causing some hiccups. It's making things incompatible with:

langchain
chroma
(and I'm guessing there are a few others)

For me, the essence of the Python client is to mesh Supabase into our Python workflows, especially in AI territory. I know a broad world of Python use cases, but this feels like a core one.
