### ISSUE TITLE
Missing a few auth providers that are already supported in supabase.

### ISSUE THREAD

**Issue by hikchoi** [supabase-community/gotrue-py#292]
# Bug report

## Describe the bug

providers `figma`, `kakao`, and `zoom` are missing from the types defined in this project.
I'm referencing the js counterpart of this repo and what the supabase dashboard tells me here. Not sure if there's another source of truth for the supported third party providers.

See [here](https://github.com/supabase-community/gotrue-py/blob/c2ed950516e4b9bee6eb8f066969049b9a361a28/gotrue/types.py#L10)

For now my workaround is to simply build the endpoint manually like so:
```
https://{BASE_URL}/auth/v1/authorize?provider=kakao
```
and it works just fine. (at least for the `kakao` provider)

## To Reproduce

I'm using part of our project's code that uses the supabase python client here as an example, but from a quick skim of both repos, I think it's simply an omission in the upstream (gotrue-py).
```python
...
from .settings import get_settings
from supabase import create_client, Client
supabase: Client = create_client(
    settings.SUPABASE_URL, 
    settings.SUPABASE_SERVICE_ROLE_KEY
)
response = supabase.auth.sign_in_with_oauth({
        "provider": "kakao",
})
...
```

will result in:
```bash
pydantic.error_wrappers.ValidationError: 1 validation error for OAuthResponse
provider
unexpected value; permitted: 'apple', 'azure', 'bitbucket', 'discord', 'facebook', 'github', 'gitlab', 'google', 'keycloak', 'linkedin', 'notion', 'slack', 'spotify', 'twitch', 'twitter', 'workos' (type=value_error.const; given=kakao; permitted=('apple', 'azure', 'bitbucket', 'discord', 'facebook', 'github', 'gitlab', 'google', 'keycloak', 'linkedin', 'notion', 'slack', 'spotify', 'twitch', 'twitter', 'workos'))
```

## Expected behavior

All supported providers work normally

## Screenshots

N/A

## System information

Irrelevant

## Additional context

Thanks for the great work, folks.

My main interest is to have the `kakao` provider work, if that provides any context at all.

I'm currently blocked with an update to the latest version because the pydantic version is too restrictive, so it would be really nice if #291 gets resolved with this as well so I can actually bump the version up to see this change active. 😄

**Comment by J0** [comment]
Hey

The pydantic version should be fixed and you should be able to use the provider. Let me know if there are still issues though.

Thanks!
