### ISSUE TITLE
ImportError: cannot import name 'SyncGoTrueClient' from 'gotrue'

### ISSUE THREAD

**Issue by McLamy** [supabase-community/gotrue-py#336]
Hey everyone,

since a couple of days I'm facing the mentioned issue in my python script.
The import comes from "from supabase import create_client, Client" and is implemented like the official supabase docs suggest:

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

 It would be great if someone can give me a hint how to fix this. Many thanks in advance!

**Comment by McLamy** [comment]
![image](https://github.com/supabase-community/gotrue-py/assets/44198876/3834ba22-8a35-4b05-b095-4ec4f30f65d6)

**Comment by J0** [comment]
Hey @McLamy,

Thanks for the query. Quick check: what version of Supabase Python are you using?

**Comment by McLamy** [comment]
Hey @J0,

thanks for getting back. The version is 1.1.1.
Your comment gave me the idea to check the modules with "pip check" which shows some incompatible dependencies. I wasn't able to find an arrangement where everything works flawlessly so I decided to delete all false modules and reinstall them and now its working again 🎉 
Still wondering how this could happened but *turning the PC off and on again* does the job 9/10 times 😛 

Thanks again for getting back and furthermore for your outstanding contributions!

**Comment by J0** [comment]
Thanks @McLamy,
Glad the issue was resolved. Going to close for now but let us know if there are further issues 🙏
