### ISSUE TITLE
Proof Key for Code Exchange (PKCE) auth flow for OAuth sign in

### ISSUE THREAD

**Issue by silentworks** [supabase-community/gotrue-py#339]
We need to add the `pkce` auth flow for the OAuth functionality to work fully server side, currently with the `implicit` flow the auth token is returned in a URL hash and since Python isn't a client-side language it cannot retrieve that token.

**Comment by J0** [comment]
Linked to #331 

Sorry I realize I haven't closed this up - will try to look at it again on friday evening

**Comment by silentworks** [comment]
This has now been merged.

**Comment by Catchmaker** [comment]
Do you have a before/after example or other docs on how we change our server-side Python code (no JS framework) to take advantage of this? e.g. was the redirect changed from #access_token to ?access_token -- or a redirect param added to SignInWithOAuthCredentials or ???
