### ISSUE TITLE
gotrue.lib directory is ignored in .gitignore

### ISSUE THREAD

**Issue by lawrencecchen** [supabase-community/gotrue-py#4]
# Bug report

## Describe the bug

The `lib/` directory is included in `.gitignore`. Not sure if this is intentional, as it also ignores the `gotrue/lib` directory, which is used in other files: https://github.com/supabase/gotrue-py/blob/main/gotrue/api.py#L6

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## Expected behavior

There should be a `gotrue/lib/constants.py` file (and maybe others?) that is listed.

**Comment by leynier** [comment]
> I think that this issue should be closed

@dreinon ⬆️

**Comment by dreinon** [comment]
@lawrencecchen Thanks for reporting the issue! We are closing it since this should already be solved.
Nevertheless, feel free to comment again if you are still experiencing issues.

**Comment by J0** [comment]
@leynier, thanks!
