### ISSUE TITLE
Mix js string with python fstring 

### ISSUE THREAD

**Issue by zodman** [supabase-community/gotrue-py#63]
https://github.com/supabase-community/gotrue-py/blob/2f94bfdbc2cf20ef50ec777bbda03face1da3e85/gotrue/_sync/api.py#L556

**Comment by zodman** [comment]
same for _async

**Comment by dreinon** [comment]
Thanks for reporting!
Can you please open a PR for these?

Remember to use conventional commits. For instance: `fix: remove $ from f-strings`

**Comment by leynier** [comment]
Thanks for the report, but please make the changes to the `_async` section because the `_sync` section is auto-generated from the `_async` using the `make build_sync` command.
