### ISSUE TITLE
bug: `delete_user` returns `Exception` event if response is Ok

### ISSUE THREAD

**Issue by songololo** [supabase-community/gotrue-py#66]
The `delete_user` method in `api.py` raises an Exception at line [558](https://github.com/supabase-community/gotrue-py/blob/4b5ce2f583ca84a972445a7cd08ffd44bbbb03c9/gotrue/_async/api.py#L558)

It does so even though the response from the http client (previous line) returns status 200.

**Comment by leynier** [comment]
@songololo What is the type of exception? `Exception` exactly?

**Comment by leynier** [comment]
Can you show a snippet code that raises this error and the content of the response?

**Comment by songololo** [comment]
Here is a minimal working example:

```python
from gotrue import User
User.parse_obj({})
```

In the original context, the response from delete user returns an OK response with status 200, but which is otherwise empty. This empty response is passed to `cls.parse_obj` in [api.py line 558](https://github.com/supabase-community/gotrue-py/blob/4b5ce2f583ca84a972445a7cd08ffd44bbbb03c9/gotrue/_async/api.py#L558), which, in turn, passes the empty `dict` to [types.py line 29](https://github.com/supabase-community/gotrue-py/blob/4b5ce2f583ca84a972445a7cd08ffd44bbbb03c9/gotrue/types.py#L29)

i.e.
```python
from gotrue import User

class MockResponse:

    @classmethod
    def raise_for_status(cls):
        return None

    @classmethod
    def json(cls):
        return {}

User.parse_response(MockResponse)
```

**Comment by leynier** [comment]
> Here is a minimal working example:
> 
> ```python
> from gotrue import User
> User.parse_obj({})
> ```
> 
> In the original context, the response from delete user returns an OK response with status 200, but which is otherwise empty. This empty response is passed to `cls.parse_obj` in [api.py line 558](https://github.com/supabase-community/gotrue-py/blob/4b5ce2f583ca84a972445a7cd08ffd44bbbb03c9/gotrue/_async/api.py#L558), which, in turn, passes the empty `dict` to [types.py line 29](https://github.com/supabase-community/gotrue-py/blob/4b5ce2f583ca84a972445a7cd08ffd44bbbb03c9/gotrue/types.py#L29)
> 
> i.e.
> ```python
> from gotrue import User
> 
> class MockResponse:
> 
>     @classmethod
>     def raise_for_status(cls):
>         return None
> 
>     @classmethod
>     def json(cls):
>         return {}
> 
> User.parse_response(MockResponse)
> ```

Thanks, we will review and fix it as soon as possible.  We will also add a test to cover that method.  Greetings.

**Comment by leynier** [comment]
Likewise, if you want to work on the fix because you need it urgently, do so.  If not, no problem, we will fix it as soon as possible.

**Comment by songololo** [comment]
Thanks. For now I've simply modified my local copy to:
```python
class BaseModelFromResponse(BaseModel):
    @classmethod
    def parse_response(cls: Type[T], response: Response) -> T:
        check_response(response)
        response_json = response.json()
        if response_json == {}:
            return None
        else:
            return cls.parse_obj(response_json)
```
But, I'm not sure how this affects the remainder of the system so I'll hold off suggesting concrete changes for now!
